CREATE TABLE FORNECEDOR
(COD_FORN INT NOT NULL PRIMARY KEY,
NOME_FORN VARCHAR(50));

CREATE TABLE PRODUTO
(COD_PROD INT NOT NULL PRIMARY KEY,
NOME_PROD VARCHAR(50) NOT NULL,
E_COMBO VARCHAR(1) NOT NULL,
VALOR_VENDA FLOAT NULL);

CREATE TABLE COMBO
(COD_PROD_COMBO INT NOT NULL REFERENCES PRODUTO(COD_PROD),
COD_PROD INT NOT NULL REFERENCES PRODUTO(COD_PROD),
QUANT INT NOT NULL,
CONSTRAINT PRI_COMBO PRIMARY KEY(COD_PROD_COMBO,COD_PROD));

CREATE TABLE TAB_PRECO
(COD_PROD INT NOT NULL REFERENCES PRODUTO(COD_PROD),
COD_FORN INT NOT NULL REFERENCES FORNECEDOR(COD_FORN),
VALOR_OFERTADO INT NOT NULL,
CONSTRAINT PRI_TAB_PRECO PRIMARY KEY(COD_PROD,COD_FORN));

CREATE TABLE PEDIDO
(COD_PEDIDO INT NOT NULL PRIMARY KEY,
COD_FORN INT NOT NULL REFERENCES FORNECEDOR(COD_FORN),
DT_PEDIDO DATE,
STATUS VARCHAR(40),
VALOR_TOTAL FLOAT);

CREATE TABLE ITEM_PEDIDO
(COD_ITEM_PEDIDO SERIAL NOT NULL PRIMARY KEY,
COD_PEDIDO INT NOT NULL REFERENCES PEDIDO(COD_PEDIDO),
COD_PROD INT NOT NULL REFERENCES PRODUTO(COD_PROD),
QUANT_COMPRADA INT NOT NULL);
