CREATE TABLE LEITOR
(COD_LEITOR INT NOT NULL PRIMARY KEY,
NOME VARCHAR(50) NOT NULL);

CREATE TABLE LIVRO
(COD_LIVRO INT NOT NULL PRIMARY KEY,
TITULO VARCHAR(50) NOT NULL);

CREATE TABLE EMPRESTIMO
(COD_EMP SERIAL NOT NULL PRIMARY KEY,
COD_LEITOR INT NOT NULL REFERENCES LEITOR(COD_LEITOR),
COD_LIVRO INT NOT NULL REFERENCES LIVRO(COD_LIVRO),
DT_EMP DATE,
DT_DEV DATE);

CREATE TABLE RESERVA
(COD_RES INT NOT NULL PRIMARY KEY,
COD_LEITOR INT NOT NULL REFERENCES LEITOR(COD_LEITOR),
COD_LIVRO INT NOT NULL REFERENCES LIVRO(COD_LIVRO),
STATUS VARCHAR(50) NOT NULL CHECK (STATUS='ativo' or STATUS='inativo'));

---------------------RESPOSTA---------------------------

